admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 8000 }


static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 443 }
      filter_chains:
        filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: ["*"]
                    routes:
                      - match:
                          prefix: "/auth.PublicApi"
                        route:
                          cluster: auth_service
                          max_grpc_timeout: 15.0s
                      - match:
                          prefix: "/api.PublicApi"
                        route:
                          cluster: api_service
                          max_grpc_timeout: 15.0s
                    cors:
                      allow_origin:
                        - "*"
                      allow_methods: GET, PUT, DELETE, POST, OPTIONS
                      allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                      enabled: true
              http_filters:
                - name: envoy.grpc_web
                - name: envoy.cors
                - name: envoy.router
        tls_context:
          common_tls_context:
            alpn_protocols:
              - h2
            tls_certificates:
              - certificate_chain:
                  filename: /etc/envoy/data/certifs/local/localhost.crt
                private_key:
                  filename: /etc/envoy/data/certifs/local/localhost.key
            validation_context:
              trusted_ca:
                filename: /etc/envoy/data/certifs/local/ca.pem


  clusters:
    - name: auth_service
      connect_timeout: 15.0s
      type: LOGICAL_DNS
      http2_protocol_options: {}
      lb_policy: round_robin
      hosts:
      - socket_address: { address: auth, port_value: 8010 }
      tls_context:
        common_tls_context:
          alpn_protocols:
          - h2
          tls_certificates:
          - certificate_chain:
              filename: /etc/envoy/data/certifs/local/auth.crt
            private_key:
              filename: /etc/envoy/data/certifs/local/auth.key
          validation_context:
            trusted_ca:
              filename: /etc/envoy/data/certifs/local/ca.pem

    - name: api_service
      connect_timeout: 15.0s
      type: LOGICAL_DNS
      http2_protocol_options: {}
      lb_policy: round_robin
      hosts:
      - socket_address: { address: api, port_value: 8020 }
      tls_context:
        common_tls_context:
          alpn_protocols:
          - h2
          tls_certificates:
          - certificate_chain:
              filename: /etc/envoy/data/certifs/local/localhost.crt
            private_key:
              filename: /etc/envoy/data/certifs/local/localhost.key
          validation_context:
            trusted_ca:
              filename: /etc/envoy/data/certifs/local/ca.pem
