version: "3"

services:
  envoy:
    build:
      context: ../../../
      dockerfile: ./infra/docker/envoy/Dockerfile
    ports:
      - "443:443"
      - "8000:8000"
    networks:
      - api-net

  account:
    build:
      context: ../../../
      dockerfile: ./infra/docker/account/Dockerfile
    command: account
    ports:
    - "8010:8010"
    networks:
    - api-net
    environment:
    - APP_ENV=development
    - SSL_CERT=/data/certifs/local/account.crt
    - SSL_KEY=/data/certifs/local/account.key
    volumes:
    - ../../../pkg:/go/src/github.com/quentinbrosse/scwgame/pkg
    - ../../../vendor:/go/src/github.com/quentinbrosse/scwgame/vendor

  api:
    build:
      context: ../../../
      dockerfile: ./infra/docker/api/Dockerfile
    command: api
    ports:
      - "8020:8020"
    networks:
      - api-net
    environment:
      - APP_ENV=development
      - SSL_CERT=/data/certifs/local/localhost.crt
      - SSL_KEY=/data/certifs/local/localhost.key
    volumes:
      - ../../../pkg:/go/src/github.com/quentinbrosse/scwgame/pkg
      - ../../../vendor:/go/src/github.com/quentinbrosse/scwgame/vendor

#  database:
#    image: mysql:8
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_DATABASE: scwgame
#      MYSQL_ONETIME_PASSWORD: true
#      MYSQL_USER: scwgame
#      MYSQL_PASSWORD: scwgame

networks:
  api-net:
