version: "3"

services:
  envoy:
    build:
      context: ../../../
      dockerfile: ./infra/docker/envoy/Dockerfile
    ports:
      - "443:443"
      - "8000:8000"
    networks:
      - scwgame-net

  account:
    build:
      context: ../../../
      dockerfile: ./infra/docker/account/Dockerfile
    command: account
    networks:
      - scwgame-net
    environment:
      APP_ENV: ${APP_ENV}
      SSL_CERT: /data/certifs/local/account.crt
      SSL_KEY: /data/certifs/local/account.key
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: database
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../../../pkg:/go/src/github.com/quentinbrosse/scwgame/pkg
      - ../../../vendor:/go/src/github.com/quentinbrosse/scwgame/vendor

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - scwgame-net
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_ONETIME_PASSWORD: "true"
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

networks:
  scwgame-net:
